/**
 * Generator Module
 * Orchestrates template merging, docx generation, and file downloading.
 */

window.DocumentGenerator = {
    /**
     * Generates a docx Blob without downloading.
     * @param {Array} docxElements - The mapped docx elements.
     * @param {string} templateId - The selected template ID.
     * @param {Object} metadata - Document metadata.
     * @returns {Promise<Blob>} The generated docx Blob.
     */
    getBlob: async function(docxElements, templateId, metadata) {
        const { Document, Packer } = window.docx;

        // 1. Get the template configuration
        const templateConfig = window.TemplateFactory[templateId] || window.TemplateFactory['corporate'];

        // 2. Let the template define the sections (Cover Page, Headers, Footers)
        let sections = [];
        if (typeof templateConfig.getSections === 'function') {
            sections = templateConfig.getSections(docxElements, metadata);
        } else {
            sections = [{
                properties: {},
                children: docxElements
            }];
        }

        // 3. Build the Document object
        const docConfig = {
            creator: metadata.author || templateConfig.creator || "BoardroomMD",
            title: metadata.title || "Generated Document",
            description: "Generated by BoardroomMD",
            styles: templateConfig.styles,
            sections: sections
        };

        if (templateConfig.background) {
            docConfig.background = templateConfig.background;
        }

        const doc = new Document(docConfig);

        // 4. Pack the document into a Blob
        try {
            return await Packer.toBlob(doc);
        } catch (error) {
            console.error("Error packing document to Blob:", error);
            throw error;
        }
    },

    /**
     * Triggers the download of a Blob.
     */
    download: function(blob, metadata) {
        const filename = metadata.title ? `${metadata.title.replace(/\s+/g, '_')}.docx` : "Document.docx";
        window.saveAs(blob, filename);
    }
};
